permalink: /blog/:year/:month/:day/:title/
title: RayHightower.com
extendedtitle: Chicago Ruby on Rails - RubyMotion - iOS - IoT
subtitle: Thoughts about Ruby, Rails, iOS, IoT, software development, and business growth.
author: Raymond T. Hightower - Chicago Ruby on Rails & iOS Developer
description: Chicago Ruby on Rails and iOS Developer

baseurl: /
  
# Social Media
github_user: rayhightower
twitter_user: rayhightower
disqus_short_name: rayhightower
google_analytics_tracking_id: UA-330946-28
linkedin_user: rayhightower
