permalink: /blog/:year/:month/:day/:title/
title: RayHightower.com
extendedtitle: Chicago Ruby on Rails - RubyMotion - iOS - IoT
subtitle: Thoughts about Ruby, Rails, iOS, the Internet of Things, software development, and business growth.
author: Raymond T. Hightower - Chicago Ruby on Rails & iOS Developer
description: Chicago Ruby on Rails and iOS Developer
  

