permalink: /blog/:year/:month/:day/:title/
title: RayHightower.com
extendedtitle: Chicago Ruby on Rails - RubyMotion - iOS - IoT
subtitle: Thoughts about Ruby, Rails, iOS, IoT, software development, and business growth.
author: Raymond T. Hightower - Chicago Ruby on Rails & iOS Developer
description: Chicago Ruby on Rails and iOS Developer

baseurl: http://rayhightower.com/rayhightower-jekyll
  
# Social Media
github_user: rayhightower
twitter_user: rayhightower
disqus_short_name: RayHightower
google_analytics_tracking_id: UA-330946-28
linkedin_user: rayhightower

markdown: redcarpet
# markdown: rdiscount
# rdiscount:
redcarpet:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb
  
# For Jekyll Plugins, per http://jekyllrb.com/docs/plugins/
# gems: [ image_tag, image_caption_tag ]  
